# Generated by Django 3.0.5 on 2020-05-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraccount_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_images'),
        ),
    ]
