export const LOGIN = "LOGIN";
export const SIGN_UP = "SIGN_UP";
export const LOG_OUT = "LOG_OUT";
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP";
export const CHANGE_RECORD_BUTTON = "CHANGE_RECORD_BUTTON";
export const COUNT_RECORDING_TIME = "COUNT_RECORDING_TIME";
export const CREATE_SAD = "CREATE_SAD";
export const GET_ALL_SADGEGRDZELO = "GET_ALL_SADGEGRDZELO";